language: python
python:
- 3.6.4
branches:
  only:
  - develop
  - master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- docker run -v $(pwd):/lambda -it chiwenchen/lambda_go_deployer /bin/bash
- source .bash_profile
- cd lambda
- go get .
- GOOS=linux go build -o main
- sam package --template-file $(pwd)/template.yaml --s3-bucket $bucket --output-template-file $output_template_file
deploy:
  provider: script
  script: aws cloudformation deploy --template-file $(pwd)/$output_template_file --stack-name $stack_name --capabilities CAPABILITY_IAM --parameter-overrides  SomeString=hello_prod
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=ap-southeast-1
  - bucket=ivan-sam-bucket-testing
  - output_template_file=serverless-output.yaml
  - stack_name=prod-sns-service
  - secure: j2vCnO0EdkwoeP8w3n8AGraFxK5P79/bxZLogF3I+Y4jX0Ey0+U4fYFjfuA9cyYWKlTW983BqCCRWnVTkYd274lCKqTZHWH+DX1BN0/NMhcKWcCA7h59VnB5cBgrcFCJ03COOVqy+HK0DysIEPcwCG3wr7rImV2cWxrvSPrvhjMYIUE8kYcabMlO+J6gu5+pgxdeJxT2N/TAwr3d3NSCn4ZiYMuw4bnJy0j2W2VqL5a1icOzk6+7Eb8/EH5rB6vsSLBfZpxLwZd6ObVCrvnFAEnHmZ2LuihdVPPqR8smvWO/py3IhzBTxlt+T2Wxm4qomOvVKhe+KOEMHcGqUjSr0VQ7MbmSP7KwybzYlkMJSem1MFe+viFJbviEjtKspcCBUheVZJa5botFEjamGP/Rs5x9WXaUqgbG7tE+wNymgMHrcWxygVTfYUFUA/A9NdFJC1S9DOhBprMezUsfCy+77NcjOZ92UDBzy9UHVhG6UxNbBM1xk1+RdyvKP030n9csTzFG2iBI2Xm0l6/SCC78Ms8f9FxmC92+eHhSyPrUmBpGxKM3/T0ly4N/MCurSoZcGJOg6qIzDUglf0M03XR3oBPZezueKqhln65HGuJMssyZCkmVabhTbceWa8QRYQCj1wLV6cEs4Ua1JjUWPE047JYsi4ndUfSOC/lElv+50Gc=
  - secure: r/MMLj1P3AydXSXJEWXfqVfFcRNd/zWdLdRJtX8mAmjhxEfZrhFXawCNieHiZ9Py50aqo0floEuCYlvuZuFOIuV97DquecrhYml5eI/8XNZGgwJSiW64EzuilyrxrDMjyUqYbWGM142hMLmdkf/aXX7KQMnzqQZej0u+UWMP5dnsWmifJGs0WWSRFk38ARblMrlypE9k4rJ9XlAx4nximywPmheAcKkDVW/ysDYc9S1qe5ENio5PpC8QD6cs0F1+Gk+GXY7DPxT9JoQ4C+oFLUxKfVz4BLULz2WLr34gBeKdTrmR3YKFQQeL6H7BNiSy/hM6PxRF1qEegEZ5/MMaRSy8F0RO3d/EnkRX/zuBhUGG4VJsssqg3/YUUJYSOqIFDQiF8sSDoa+PJHSCY11Hh9ob9rIqpx5jmRfl9WmKAhd0k5egafDqUh9xUng09t2nClZX8tM4lX/nV2z0SftPuyi5j+hIBI3ToZPuecgc5z2OZ1Cqi0vF4ksoufOqMz4v/7XaZ3/2DhUI3xGRd3XqIB4F3AS2ZNlzUFuAwUsO9lafks0LAh1xOQvHK60HOj4w9B6rlf6Eaz9lXTM6QGYJnER2HySCYP2D3GzrRb0D1lHry0s161fFfak7mpgpupCK9Joe7kuEYpj4IxT213ufSB+KWuNwY6hXpKHsdcCO5BI=
