AWSTemplateFormatVersion: '2010-09-09'
Description: An example to demo deploy multiple stage
Parameters:
  DB:
    Type: String
Resources:
  ExampleAPI:
    FunctionName: ExampleLambda
    Properties:
      CodeUri: s3://ivan-sam-bucket-testing/e6dbdac913dbcb70e5cda258a9e05af8
      Environment:
        Variables:
          DBConnection:
            Ref: DB
          HELLO: hello from local
      Events:
        HelloHandler:
          Properties:
            Method: get
            Path: /hello
          Type: Api
        RootHandler:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: main
      Role: arn:aws:iam::274571492950:role/ssm_full_access
      Runtime: go1.x
    Type: AWS::Serverless::Function
  ExampleAPIRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
